import { useState } from 'react'
import { ArrowDownRight, Download, Github, Linkedin, Mail, Menu, X } from 'lucide-react'
import { projects, skillGroups, type Project } from './data/projects'

const email = 'dja6@rice.edu'
const github = 'https://github.com/devinja13'
const linkedin = 'https://www.linkedin.com/in/devin-abraham/'
const resumeUrl = `${import.meta.env.BASE_URL}resume.pdf`
const profileImageUrl = `${import.meta.env.BASE_URL}images/devin-profile.jpg`

function Navbar() {
  const [open, setOpen] = useState(false)
  const links = [{ href: '#top', label: 'Home' }, { href: '#projects', label: 'Projects' }, { href: '#skills', label: 'Skills' }, { href: '#contact', label: 'Resume' }]
  const close = () => setOpen(false)
  return <header className="sticky top-0 z-30 border-b border-line/80 bg-paper/90 backdrop-blur"><div className="page flex h-16 items-center justify-between"><a href="#top" className="flex items-center gap-3" onClick={close} aria-label="Devin Abraham home"><span className="grid h-8 w-8 place-items-center rounded-full bg-ink font-mono text-[10px] font-bold text-paper">DA</span><span className="font-mono text-xs font-medium tracking-[.14em] text-ink">DEVIN ABRAHAM</span></a><nav className="hidden items-center gap-7 md:flex">{links.map(link => <a key={link.href} href={link.href} className="nav-link">{link.label}</a>)}</nav><button className="grid h-9 w-9 place-items-center md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={20} /> : <Menu size={20} />}</button></div>{open && <nav className="border-t border-line bg-paper px-6 py-4 md:hidden">{links.map(link => <a key={link.href} href={link.href} onClick={close} className="block py-3 font-mono text-xs uppercase tracking-widest">{link.label}</a>)}</nav>}</header>
}

function SectionHeader({ eyebrow, title, body }: { eyebrow: string; title: string; body?: string }) { return <div className="section-header"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{body && <p className="section-body">{body}</p>}</div> }

function ProjectCard({ project, number }: { project: Project; number: number }) {
  const reportUrl = project.reportFile?.startsWith('http') ? project.reportFile : project.reportFile ? `${import.meta.env.BASE_URL}${project.reportFile}` : undefined
  const imageUrl = project.imageFile ? `${import.meta.env.BASE_URL}${project.imageFile}` : undefined
  return <article className={`case-study art-${project.accent}`}>
    <div className="case-study-art">{imageUrl ? <img className="report-image" src={imageUrl} alt={`${project.title} report visual`} /> : <NFLVisualization />}<span className="case-number">0{number}</span></div>
    <div className="case-study-content"><div className="flex items-start justify-between gap-6"><div><p className="eyebrow !mb-3">{project.eyebrow} · {project.year}</p><h3 className="font-display text-4xl leading-[.95] tracking-[-.03em] text-ink md:text-5xl">{project.title}</h3></div><span className="project-index">0{number}</span></div><p className="mt-6 max-w-2xl text-lg leading-8 text-ink/75">{project.summary}</p><div className="case-study-grid"><CaseStudyItem label="Problem" content={project.challenge} /><CaseStudyItem label="Approach" content={project.approach.join(' ')} /><CaseStudyItem label="Result" content={project.outcome} /></div><div className="mt-8 flex flex-wrap items-center justify-between gap-5 border-t border-ink/15 pt-5"><div className="flex flex-wrap gap-2">{project.tools.map(tool => <span className="tag" key={tool}>{tool}</span>)}</div><div className="flex items-center gap-3">{project.githubUrl && <a className="text-link" href={project.githubUrl} target="_blank" rel="noreferrer">GitHub <Github size={14} /></a>}{reportUrl ? <a className="text-link" href={reportUrl} target="_blank" rel="noreferrer">{project.reportLabel} <Download size={14} /></a> : <span className="text-link-muted">Report / demo soon</span>}{project.videoUrl && <a className="text-link" href={project.videoUrl} target="_blank" rel="noreferrer">Video <ArrowDownRight size={14} /></a>}</div></div></div>
  </article>
}

function NFLVisualization() { return <div className="football-field" aria-label="Receiver and defender tracking visualization"><span className="route route-one" /><span className="route route-two" /><i className="player offense-one" /><i className="player offense-two" /><i className="player defense-one" /><i className="player defense-two" /><b>TRACKING DATA</b></div> }

function CaseStudyItem({ label, content }: { label: string; content: string }) { return <div><p className="eyebrow !mb-3">{label}</p><p className="text-sm leading-7 text-ink/70">{content}</p></div> }
function SkillGroup({ title, skills, number }: { title: string; skills: string[]; number: number }) { return <div className="skill-group"><span className="font-mono text-[10px] text-signal">0{number}</span><h3>{title}</h3><div className="mt-4 flex flex-wrap gap-2">{skills.map(skill => <span className="skill-tag" key={skill}>{skill}</span>)}</div></div> }

function App() { return <div id="top" className="min-h-screen overflow-x-hidden"><Navbar /><main>
  <section className="page hero-section"><div><p className="eyebrow">Rice University · Operations Research & Data Science</p><h1>Optimization and data systems for <em>applied decision-making.</em></h1><div className="hero-copy space-y-4"><p>I’m Devin Abraham, an Operations Research student at Rice University with a minor in Data Science. I’m originally from Chicago, and I’ve always been drawn to problems that require both creativity and structure, including optimizing systems, analyzing data, and building models that help people make better decisions.</p><p>I’m especially interested in optimization, data science, and machine learning, and I enjoy working on projects that turn complex real-world problems into something more understandable and useful. Some of my favorite work has involved elevator routing, urban tree-planting optimization, NFL tracking data, and reinforcement learning agents for card games like Euchre.</p><p>Outside of academics and projects, I like staying active through sports, working out, and running. I also love reading and cooking, which give me a different kind of space to learn, experiment, and be creative.</p></div><div className="mt-8 flex flex-wrap gap-3"><a className="button-primary" href="#projects">View projects <ArrowDownRight size={16} /></a><a className="button-quiet" href={resumeUrl} target="_blank" rel="noreferrer">Resume <Download size={15} /></a><a className="button-quiet" href={github} target="_blank" rel="noreferrer"><Github size={15} /> GitHub</a><a className="button-quiet" href={linkedin} target="_blank" rel="noreferrer"><Linkedin size={15} /> LinkedIn</a></div></div><div className="hero-photo-card"><img src={profileImageUrl} alt="Devin Abraham" /></div></section>

  <section id="projects" className="page scroll-section"><SectionHeader eyebrow="01 / Featured projects" title="Selected technical projects." body="These projects translate complex constraints into optimization models, simulations, and analytical workflows that support clearer decisions." /><div className="mt-14 space-y-10">{projects.map((project, index) => <ProjectCard key={project.slug} project={project} number={index + 1} />)}</div></section>

  <section id="skills" className="bg-ink text-paper"><div className="page scroll-section"><SectionHeader eyebrow="03 / Skills" title="Technical capabilities." body="Methods and tools used to formulate models, build data workflows, evaluate policies, and communicate results." /><div className="mt-12 grid gap-x-10 gap-y-8 md:grid-cols-2 xl:grid-cols-3">{skillGroups.map((group, index) => <SkillGroup key={group.title} number={index + 1} {...group} />)}</div></div></section>

  <section id="contact" className="contact-section"><div className="page"><p className="eyebrow">04 / Resume & contact</p><div className="flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><h2>Open to technical roles in <em>optimization and data science.</em></h2><div className="flex flex-wrap gap-3"><a className="button-primary" href={resumeUrl} target="_blank" rel="noreferrer">Resume <Download size={16} /></a><a className="button-quiet" href={github} target="_blank" rel="noreferrer">GitHub <Github size={15} /></a><a className="button-quiet" href={linkedin} target="_blank" rel="noreferrer">LinkedIn <Linkedin size={15} /></a><a className="button-quiet" href={`mailto:${email}`}>Email <Mail size={15} /></a></div></div></div></section>
</main><footer className="border-t border-line"><div className="page flex flex-col gap-3 py-7 text-xs text-ink/55 sm:flex-row sm:items-center sm:justify-between"><span className="font-mono">© {new Date().getFullYear()} DEVIN ABRAHAM</span><span>Operations Research · Data Science · Rice University</span></div></footer></div> }

export default App
