import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowLeft, ArrowUpRight, Download, Mail, Menu, X } from 'lucide-react'
import { Link, NavLink, Route, Routes, useParams } from 'react-router-dom'
import { projects, type Project } from './data/projects'

const initials = 'AM'
const navLinks = [{ to: '/', label: 'Home' }, { to: '/projects', label: 'Projects' }, { to: '/about', label: 'About' }, { to: '/resume', label: 'Resume' }]

function Shell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false)
  useEffect(() => { setOpen(false) }, [])
  return <div className="min-h-screen overflow-x-hidden">
    <header className="sticky top-0 z-30 border-b border-line/80 bg-paper/90 backdrop-blur">
      <div className="page flex h-16 items-center justify-between">
        <Link to="/" className="group flex items-center gap-3" aria-label="Alex Morgan home"><span className="grid h-8 w-8 place-items-center rounded-full bg-ink font-mono text-[10px] font-bold text-paper">{initials}</span><span className="font-mono text-xs font-medium tracking-[.14em] text-ink">ALEX MORGAN</span></Link>
        <nav className="hidden items-center gap-7 md:flex">{navLinks.map(link => <NavLink key={link.to} to={link.to} end={link.to === '/'} className={({ isActive }) => `nav-link ${isActive ? 'text-ink' : ''}`}>{link.label}</NavLink>)}</nav>
        <button className="grid h-9 w-9 place-items-center md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={20} /> : <Menu size={20} />}</button>
      </div>
      {open && <nav className="border-t border-line bg-paper px-6 py-5 md:hidden">{navLinks.map(link => <NavLink key={link.to} to={link.to} end={link.to === '/'} className="block py-3 font-mono text-xs uppercase tracking-widest">{link.label}</NavLink>)}</nav>}
    </header>
    <main>{children}</main>
    <footer className="border-t border-line"><div className="page flex flex-col gap-5 py-8 text-xs text-ink/60 sm:flex-row sm:items-center sm:justify-between"><p className="font-mono">© {new Date().getFullYear()} ALEX MORGAN</p><div className="flex items-center gap-5"><a href="mailto:alex.morgan@example.com" className="footer-link">Email</a><a href="https://github.com" target="_blank" rel="noreferrer" className="footer-link">GitHub</a><a href="https://linkedin.com" target="_blank" rel="noreferrer" className="footer-link">LinkedIn</a></div><p>Designed for useful work.</p></div></footer>
  </div>
}

function Label({ children }: { children: React.ReactNode }) { return <p className="mb-5 font-mono text-[10px] font-medium uppercase tracking-[.19em] text-signal">{children}</p> }

function ProjectCard({ project, index = 0 }: { project: Project; index?: number }) {
  return <Link to={`/projects/${project.slug}`} className="project-card group"><div className={`project-art art-${project.accent}`}><span className="art-index">0{index + 1}</span><span className="art-shape" /></div><div className="flex items-start justify-between gap-4 pt-5"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-ink/55">{project.category} · {project.year}</p><h3 className="mt-2 font-display text-2xl leading-none text-ink">{project.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-ink/70">{project.summary}</p></div><ArrowUpRight className="mt-1 shrink-0 transition-transform duration-200 group-hover:-translate-y-1 group-hover:translate-x-1" size={19} /></div></Link>
}

function Home() { const featured = projects.filter(project => project.featured); return <>
  <section className="page grid min-h-[calc(100vh-4rem)] items-center gap-12 py-16 md:grid-cols-[1.25fr_.75fr] md:py-24">
    <div><Label>Operations research · data science</Label><h1 className="max-w-4xl font-display text-[clamp(3.4rem,8vw,7.3rem)] leading-[.87] tracking-[-.045em] text-ink">Making complex systems <em className="font-display text-signal">legible.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-ink/70">I’m Alex, an operations research and data science student interested in models that turn uncertainty into better decisions.</p><div className="mt-9 flex flex-wrap gap-4"><Link className="button-primary" to="/projects">Explore projects <ArrowDownRight size={17} /></Link><Link className="button-quiet" to="/about">About me</Link></div></div>
    <div className="relative mx-auto w-full max-w-md"><div className="hero-grid"><div className="hero-line hero-line-a" /><div className="hero-line hero-line-b" /><div className="hero-dot hero-dot-a" /><div className="hero-dot hero-dot-b" /><div className="hero-node">01</div><p className="absolute bottom-4 left-5 font-mono text-[10px] uppercase tracking-[.15em] text-ink/55">Human decisions,<br />quantified thoughtfully</p></div></div>
  </section>
  <section className="border-y border-line bg-white/30"><div className="page grid gap-10 py-14 sm:grid-cols-2 lg:grid-cols-4"><Stat value="3.91" label="GPA / 4.00" /><Stat value="12+" label="data projects" /><Stat value="4" label="research areas" /><Stat value="2026" label="expected graduation" /></div></section>
  <section className="page py-20 md:py-28"><div className="mb-11 flex items-end justify-between gap-6"><div><Label>Selected work</Label><h2 className="section-title">Recent investigations</h2></div><Link to="/projects" className="hidden items-center gap-2 font-mono text-xs uppercase tracking-wider text-ink hover:text-signal sm:flex">All projects <ArrowUpRight size={15} /></Link></div><div className="grid gap-x-7 gap-y-12 md:grid-cols-3">{featured.map((project, index) => <ProjectCard key={project.slug} project={project} index={index} />)}</div><Link to="/projects" className="button-quiet mt-10 sm:hidden">All projects <ArrowUpRight size={16} /></Link></section>
  <section className="border-y border-line bg-ink text-paper"><div className="page grid gap-12 py-20 md:grid-cols-[.8fr_1.2fr] md:py-24"><div><Label>Working toolkit</Label><h2 className="font-display text-5xl leading-[.95]">Methods, code,<br />and context.</h2></div><div className="grid grid-cols-2 gap-x-8 gap-y-8 sm:grid-cols-3">{[['Optimization', 'Linear programming\nNetwork models\nSimulation'], ['Data science', 'Python · R\nStatistical learning\nForecasting'], ['Data systems', 'SQL · dbt\nData modeling\nQuality checks'], ['Communication', 'Tableau · QGIS\nTechnical writing\nStakeholder research'], ['Research', 'Experiment design\nLiterature review\nSpatial analysis'], ['Always learning', 'Causal inference\nDecision analysis\nMLOps']].map(([title, detail], i) => <div key={title} className="border-t border-paper/25 pt-3"><span className="font-mono text-[10px] text-signal">0{i + 1}</span><h3 className="mt-5 text-sm font-medium">{title}</h3><p className="mt-2 whitespace-pre-line text-xs leading-5 text-paper/60">{detail}</p></div>)}</div></div></section>
  <section className="page py-20 md:py-28"><Label>Let’s connect</Label><div className="flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><h2 className="max-w-3xl font-display text-5xl leading-[.95] tracking-tight md:text-7xl">Have a problem worth <em className="text-moss">studying?</em></h2><a className="button-primary shrink-0" href="mailto:alex.morgan@example.com">Get in touch <Mail size={17} /></a></div></section>
</> }

function Stat({ value, label }: { value: string; label: string }) { return <div><p className="font-display text-4xl text-ink">{value}</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.13em] text-ink/55">{label}</p></div> }

function Projects() { const [filter, setFilter] = useState('All'); const filters = ['All', 'Optimization', 'Machine Learning', 'Data Engineering', 'Research']; const visible = filter === 'All' ? projects : projects.filter(p => p.category === filter); return <section className="page py-16 md:py-24"><div className="max-w-3xl"><Label>Archive / 2023—2024</Label><h1 className="section-title text-5xl md:text-7xl">Projects and studies</h1><p className="mt-6 text-lg leading-8 text-ink/70">A collection of applied work across optimization, forecasting, spatial analysis, and data systems.</p></div><div className="mt-12 flex flex-wrap gap-2 border-y border-line py-4">{filters.map(item => <button onClick={() => setFilter(item)} key={item} className={`filter-chip ${filter === item ? 'filter-active' : ''}`}>{item}</button>)}</div><p className="mt-7 font-mono text-[10px] uppercase tracking-[.14em] text-ink/50">{visible.length.toString().padStart(2, '0')} projects shown</p><div className="mt-8 grid gap-x-8 gap-y-14 md:grid-cols-2">{visible.map((project, index) => <ProjectCard key={project.slug} project={project} index={index} />)}</div></section> }

function ProjectDetail() { const { slug } = useParams(); const project = projects.find(p => p.slug === slug); if (!project) return <NotFound />; return <section><div className={`project-detail-hero art-${project.accent}`}><div className="page relative z-10 py-14 md:py-20"><Link to="/projects" className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-ink/70 hover:text-signal"><ArrowLeft size={14} /> All projects</Link><div className="mt-20 max-w-4xl"><p className="font-mono text-xs uppercase tracking-[.16em] text-ink/60">{project.eyebrow} · {project.year}</p><h1 className="mt-4 font-display text-6xl leading-[.9] tracking-tight md:text-8xl">{project.title}</h1></div></div></div><div className="page grid gap-14 py-16 md:grid-cols-[.7fr_1.3fr] md:py-24"><aside className="space-y-8"><div><p className="meta-label">Category</p><p className="mt-2 text-sm">{project.category}</p></div><div><p className="meta-label">Tools</p><div className="mt-3 flex flex-wrap gap-2">{project.tools.map(tool => <span className="tag" key={tool}>{tool}</span>)}</div></div></aside><article className="max-w-2xl"><p className="font-display text-3xl leading-tight text-ink">{project.description}</p><DetailBlock title="The question"><p>{project.challenge}</p></DetailBlock><DetailBlock title="Approach"><ol className="space-y-4">{project.approach.map((item, i) => <li className="flex gap-4" key={item}><span className="font-mono text-xs text-signal">0{i + 1}</span><span>{item}</span></li>)}</ol></DetailBlock><DetailBlock title="Result"><p>{project.outcome}</p></DetailBlock><div className="grid grid-cols-3 border-y border-line py-7">{project.metrics.map(metric => <div key={metric.label}><p className="font-display text-3xl">{metric.value}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[.1em] text-ink/55">{metric.label}</p></div>)}</div></article></div><div className="border-t border-line"><div className="page flex flex-col gap-5 py-12 sm:flex-row sm:items-center sm:justify-between"><p className="font-display text-2xl">Next in the archive</p><Link className="button-primary" to={`/projects/${projects[(projects.indexOf(project) + 1) % projects.length].slug}`}>View another project <ArrowUpRight size={16} /></Link></div></div></section> }
function DetailBlock({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-12 border-t border-line pt-5"><h2 className="font-mono text-[10px] uppercase tracking-[.15em] text-signal">{title}</h2><div className="mt-5 text-[15px] leading-7 text-ink/75">{children}</div></section> }

function About() { return <section className="page py-16 md:py-24"><div className="grid gap-14 md:grid-cols-[.82fr_1.18fr]"><div><Label>About</Label><h1 className="section-title text-5xl md:text-7xl">Curious about the machinery behind everyday life.</h1></div><div><p className="font-display text-3xl leading-tight">I’m an operations research and data science student who enjoys tracing a messy question back to its structure.</p><p className="mt-7 text-base leading-8 text-ink/70">My interests sit where mathematical modeling meets public-facing decisions: transportation, supply chains, energy, and the systems that shape how people move through the world. I’m happiest when a project requires both analytical rigor and genuine listening.</p><p className="mt-5 text-base leading-8 text-ink/70">At university, I study optimization, probability, statistical learning, and the quiet art of explaining results clearly. Outside class, you’ll find me tinkering with maps, collecting interesting data visualizations, or looking for the best neighborhood coffee shop.</p></div></div><div className="mt-20 grid gap-px overflow-hidden border border-line bg-line md:grid-cols-3"><Info title="Education" body="B.S. Operations Research & Data Science\nExpected 2026" /><Info title="Currently exploring" body="Robust optimization\nGeospatial analytics\nCausal inference" /><Info title="Based in" body="Chicago, Illinois\nOpen to internships" /></div><div className="mt-20 border-t border-line pt-10"><Label>Principles</Label><div className="grid gap-8 md:grid-cols-3">{[['Start with the decision', 'A model should serve a real choice, not only demonstrate technical complexity.'], ['Keep the human in view', 'Good analysis makes room for context, constraints, and the people affected.'], ['Show the work', 'Transparent assumptions make findings stronger and collaboration easier.']].map(([title, body], i) => <div key={title}><span className="font-mono text-xs text-signal">0{i + 1}</span><h2 className="mt-5 font-display text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-ink/65">{body}</p></div>)}</div></div></section> }
function Info({ title, body }: { title: string; body: string }) { return <div className="bg-paper p-7"><p className="meta-label">{title}</p><p className="mt-5 whitespace-pre-line text-sm leading-7">{body}</p></div> }

function Resume() { const resumeUrl = `${import.meta.env.BASE_URL}resume.pdf`; return <section className="page grid min-h-[calc(100vh-9rem)] items-center py-16 md:py-24"><div className="grid gap-12 border-y border-line py-12 md:grid-cols-[1.1fr_.9fr] md:py-20"><div><Label>Curriculum vitae</Label><h1 className="section-title text-5xl md:text-7xl">The short version.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-ink/70">A concise overview of my education, technical toolkit, research interests, and experience.</p><a className="button-primary mt-9" href={resumeUrl} target="_blank" rel="noreferrer">Open résumé PDF <Download size={17} /></a><p className="mt-4 font-mono text-[10px] uppercase tracking-[.1em] text-ink/45">Place your file at public/resume.pdf</p></div><div className="resume-sheet"><div className="flex items-start justify-between"><span className="font-display text-2xl">Alex Morgan</span><span className="font-mono text-[9px] tracking-widest">RÉSUMÉ</span></div><div className="mt-12 space-y-6">{['Education', 'Experience', 'Selected skills', 'Projects'].map((item, i) => <div key={item} className="border-t border-ink/15 pt-3"><p className="font-mono text-[9px] uppercase tracking-wider text-signal">0{i + 1} / {item}</p><div className="mt-3 h-2 w-full rounded bg-ink/10" /><div className="mt-2 h-2 w-4/5 rounded bg-ink/10" /></div>)}</div></div></div></section> }
function NotFound() { return <section className="page grid min-h-[60vh] place-items-center py-20 text-center"><div><Label>404</Label><h1 className="section-title">This page wandered off the map.</h1><Link to="/" className="button-primary mt-8">Back home <ArrowLeft size={16} /></Link></div></section> }

export default function App() { return <Shell><Routes><Route path="/" element={<Home />} /><Route path="/projects" element={<Projects />} /><Route path="/projects/:slug" element={<ProjectDetail />} /><Route path="/about" element={<About />} /><Route path="/resume" element={<Resume />} /><Route path="*" element={<NotFound />} /></Routes></Shell> }
